server:
  port: 8001

spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://192.168.192.2:30088} # VPN

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}